# Generated by Django 5.2.12 on 2026-03-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0005_scenario_video_triplet_schema_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_points', 'username'],
            },
        ),
        migrations.CreateModel(
            name='CategoryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='content.category')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_stats', to='players.player')),
            ],
            options={
                'ordering': ['category_id'],
                'unique_together': {('player', 'category')},
            },
        ),
    ]
