# Generated by Django 5.2.12 on 2026-03-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_scenario_followup_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='follow_up_caption',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='follow_up_image_url',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='follow_up_video_url',
        ),
    ]
