# Generated by Django 5.2.12 on 2026-03-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_scenario_followup_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='follow_up_caption',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='follow_up_image_url',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='follow_up_video_url',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='video_url',
        ),
        migrations.AddField(
            model_name='scenario',
            name='correct_video_url',
            field=models.CharField(blank=True, default='', help_text='Video played after the child picks the correct answer', max_length=500),
        ),
        migrations.AddField(
            model_name='scenario',
            name='question_video_url',
            field=models.CharField(blank=True, default='', help_text='Video played while the child watches the question scene', max_length=500),
        ),
        migrations.AddField(
            model_name='scenario',
            name='wrong_video_url',
            field=models.CharField(blank=True, default='', help_text='Video played after the child picks a wrong answer', max_length=500),
        ),
    ]
