# Generated by Django 5.2.12 on 2026-03-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_scenario_video_triplet_schema_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short description of the scenario media (used for AI matching)'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Image shown during question phase (fallback when no question_video_url)', max_length=500),
        ),
        migrations.AddField(
            model_name='scenario',
            name='image_url_correct',
            field=models.CharField(blank=True, default='', help_text='Image shown after a correct choice (fallback when no correct_video_url)', max_length=500),
        ),
        migrations.AddField(
            model_name='scenario',
            name='image_url_wrong',
            field=models.CharField(blank=True, default='', help_text='Image shown after a wrong choice (fallback when no wrong_video_url)', max_length=500),
        ),
    ]
