# Generated by Django 5.2.12 on 2026-03-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_scenario_description_scenario_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='tip',
            field=models.TextField(blank=True, default='', help_text='Safety advice shown after answering'),
        ),
    ]
